dist: xenial
language: java
sudo: false
jdk: openjdk15
install: true
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
