dist: xenial
language: java
sudo: false
jdk: openjdk15.0.1
install: true
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
script:
  - mvn clean package sonar:sonar -P sonar
